seed : 42

data : 
  train_batch_size : 16
  val_batch_size : 16
  test_batch_size : 16
  tokenizer_max_len : 128

train :
  num_train_epoch : 3
  weight_decay : 0.01
  learning_rate : 5e-5
  lr_scheduler : stepLR

model :
  model_name : ainize/klue-bert-base-re

wandb :
  project_name : klue-bert-base_tuning

path:
  model : /opt/ml/level2_klue-nlp-08/checkpoint/ainize_klue-bert-base-re/2023-05-12 15.43.25/epoch=2-val_micro_f1=65.08.ckpt
  train : ./dataset/train/new_train.csv
  dev : ./dataset/train/new_dev.csv
  test : ./dataset/test/test_data.csv

  
