data_path_list:
  - /Users/kimjuwon/Github/NaverBoostCamp_KLUE/colab_klue/level2_klue-nlp-08/prediction/tapt_sangwon.csv
  - /Users/kimjuwon/Github/NaverBoostCamp_KLUE/colab_klue/level2_klue-nlp-08/prediction/hj_submission.csv
  - /Users/kimjuwon/Github/NaverBoostCamp_KLUE/colab_klue/level2_klue-nlp-08/prediction/submission(2).csv

model_f1_score: 
  - 73.62
  - 73.06
  - 72.7

save_path:
  ./prediction/ensemble_BestofBest_possibility.csv

mode : 
  #hard_voting 
  possibility 
  #weighted_score