data_path_list:
  - ./prediction/ensemble_material_1.csv
  - ./prediction/ensemble_material_2.csv
  - ./prediction/ensemble_material_3.csv

model_f1_score: 
  - 100.00 # ensemble_material_1 f1-score 
  - 100.00 # ensemble_material_2 f1-score
  - 100.00 # ensemble_material_3 f1-score

save_path:
  ./prediction/ensemble_output.csv

mode : 
  hard_voting 
  #soft_voting
  #weighted_score