seed : 42

data : 
  train_batch_size : 16
  val_batch_size : 16
  test_batch_size : 16
  tokenizer_max_len : 128

train :
  num_train_epoch : 7
  weight_decay : 0.01
  learning_rate : 5e-5
  lr_scheduler : stepLR

model :
  model_name : kykim/electra-kor-base

wandb :
  project_name : kykim-electra-kor-base_tuning

path:
  model : .
  train : ./dataset/train/new_train.csv
  dev : ./dataset/train/new_dev.csv
  test : ./dataset/test/test_data.csv

  
